FROM ubuntu

#remove any old entry of webupd8team
RUN rm -f /etc/apt/sources.list.d/webupd8team-java.list

# Update & install packages
RUN apt-get update -y && \
        DEBIAN_FRONTEND=noninteractive apt-get install -fqy --no-install-recommends software-properties-common python-software-properties && \
        add-apt-repository ppa:webupd8team/java -y && \
        apt-get update -y && \
        echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
        DEBIAN_FRONTEND=noninteractive apt-get install -fqy --no-install-recommends oracle-java8-installer && \
        DEBIAN_FRONTEND=noninteractive apt-get install -fqy --no-install-recommends oracle-java8-set-default && \
        DEBIAN_FRONTEND=noninteractive apt-get install -fqy maven git && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*

RUN mkdir -p /code
WORKDIR /code
RUN git clone https://github.com/qach1/Logs.git
WORKDIR Logs
RUN mvn clean package -Dmaven.test.skip=true
#RUN find .
CMD ["java", "-jar", "./target/Logs-0.0.1-SNAPSHOT.jar"]